#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Provision the ATI Flask app under IIS using a Python 3.14 virtual environment + wfastcgi.

.DESCRIPTION
    Idempotent. Run from an ELEVATED PowerShell on the IIS server. It:
      1. Creates a venv from the all-users Python 3.14, in a location IIS can read
         (NOT under "C:\Program Files", which isn't writable -> pip silently does a
          per-user install the app-pool identity can't see).
      2. Installs wfastcgi + the app's dependencies INTO the venv.
         - Default: install from requirements.txt (normalizes a UTF-16 file to UTF-8 first).
         - -RelaxPins: install only the app's real runtime deps, UNPINNED, so pip grabs
           clean 3.14 wheels. Use this when the 2024 freeze has dead pins (e.g. pywin32==306
           has no 3.14 build) or dev cruft (Jupyter, ipython, debugpy) the app never imports.
      3. Registers the venv's wfastcgi as an IIS FastCGI application (+ sane timeouts).
      4. Ensures an app pool set to "No Managed Code".
      5. Writes the site web.config: the handler's scriptProcessor EXACTLY matches the
         FastCGI app, the wfastcgi appSettings, AND the app's full runtime config
         (FLASK_*/DATABASE_URL/AUTH_*/...). In production this <appSettings> block is the
         SINGLE SOURCE OF TRUTH (app/config_gateway.py reads it). Secrets are operator-
         supplied and PRESERVED across re-runs; never generated or stored in source.
      6. Grants IIS_IUSRS read/execute on the app + venv, and write on the log file.
      7. Verifies the app imports under the venv, then recycles the pool.

.EXAMPLE
    .\Setup-AtiIis.ps1 -RelaxPins -SiteName "ati"
#>

[CmdletBinding()]
param(
    [string] $PythonExe    = 'C:\Program Files\Python314\python.exe',
    [string] $SiteRoot     = 'C:\www\ati',                 # holds web.config + wsgi.py; the PYTHONPATH root
    [string] $VenvPath     = 'C:\www\ati\venv314',
    [string] $Requirements = 'C:\www\ati\app\requirements.txt',
    [string] $WsgiHandler  = 'wsgi.application',            # wsgi.py exposes 'application'
    [string] $LogFile      = 'C:\www\ati\wfastcgi.log',
    [string] $AppPoolName  = 'ati',
    [string] $SiteName     = '',                            # optional: assign the pool to this IIS site
    [string] $WsgiDebug    = '1',                           # 1 while bringing up; set 0 in production
    [switch] $RelaxPins,                                    # install the real runtime deps UNPINNED (recommended on 3.14)
    [switch] $SkipWebConfig,                                # don't (re)write SiteRoot\web.config

    # --- App config written into web.config <appSettings>: the PRODUCTION single source
    #     of truth (app/config_gateway.py reads it). Operator-supplied; on a re-run any
    #     value omitted is PRESERVED from the existing web.config. ---
    [string] $FlaskSecretKey      = '',                     # REQUIRED, 64 hex. Never generated by this script.
    [string] $DatabaseUrl         = '',                     # REQUIRED. bolt://USER:PASSWORD@HOST:7687
    [string] $Neo4jDatabase       = 'neo4j',
    [string] $FlaskEnv            = 'production',
    [string] $AuthEnforced        = '1',
    [string] $AuthProvider        = 'local',
    [string] $AuthAdmins          = '',                     # comma-separated usernames / employee_ids
    [string] $AuthAllowedUsers    = '',                     # empty = any active account may log in
    [string] $AuthDbPath          = 'C:\www\ati\data\auth_users.sqlite3',
    [string] $AuthSessionHours    = '12',
    [string] $SessionCookieSecure = '0',                    # 1 only once the site has HTTPS
    [string] $CorsOrigins         = '',                     # usually empty for same-origin IIS
    [string] $Debug               = 'False',
    [string] $Testing             = 'False',

    # Asana connector (the /asana endpoint). Empty unless the connector is used.
    [string] $AsanaAccessToken    = '',                     # Personal Access Token
    [string] $AsanaWorkspaceGid   = '',
    [string] $AsanaTeamGid        = '',                     # only for organization workspaces
    [string] $AsanaBaseUrl        = ''                      # blank = default API base
)

$ErrorActionPreference = 'Stop'
function Info($m) { Write-Host "[*] $m" -ForegroundColor Cyan }
function Good($m) { Write-Host "[+] $m" -ForegroundColor Green }
function Warn($m) { Write-Host "[!] $m" -ForegroundColor Yellow }

# --- 0. Preflight ----------------------------------------------------------
if (-not (Test-Path $PythonExe)) {
    throw "Python not found at '$PythonExe'. Install Python 3.14 (all users) or pass -PythonExe."
}
Import-Module WebAdministration -ErrorAction Stop
$venvPy   = Join-Path $VenvPath 'Scripts\python.exe'
$wfastcgi = Join-Path $VenvPath 'Lib\site-packages\wfastcgi.py'
if (-not (Test-Path (Join-Path $SiteRoot 'wsgi.py'))) {
    Warn "No wsgi.py at '$SiteRoot' - WSGI_HANDLER='$WsgiHandler' needs a wsgi.py in SiteRoot exposing 'application'."
}

# --- 1. Create the venv ----------------------------------------------------
if (Test-Path $venvPy) {
    Info "venv already present at $VenvPath"
} else {
    Info "Creating venv at $VenvPath"
    & $PythonExe -m venv $VenvPath
    if ($LASTEXITCODE -ne 0) { throw "venv creation failed (exit $LASTEXITCODE)." }
}
Good "venv python: $venvPy"

# --- 2. Install dependencies into the venv ---------------------------------
Info "Upgrading pip / setuptools / wheel (so pip can find 3.14 wheels)"
& $venvPy -m pip install --upgrade pip setuptools wheel
if ($LASTEXITCODE -ne 0) { throw "pip upgrade failed." }

Info "Installing wfastcgi into the venv"
& $venvPy -m pip install wfastcgi
if ($LASTEXITCODE -ne 0) { throw "wfastcgi install failed." }

if ($RelaxPins) {
    # The app's actual runtime imports (derived from the code), current versions -> 3.14 wheels.
    # Web framework + graph + the feature libs (export / viz / excel / charts / AI / logging).
    $core = @(
        # The app's runtime deps, pinned to the 3.14-verified versions (matches app/requirements.txt).
        'Flask==3.1.3','Flask-Cors==6.0.5','waitress==3.0.2','neomodel==6.1.0','neo4j==6.1.0',
        'python-dotenv','requests','PyYAML','python-dateutil',
        'networkx','pyvis','openpyxl','plotly','openai','seqlog'
    )
    Info "Installing the app's runtime deps UNPINNED: $($core -join ', ')"
    & $venvPy -m pip install $core
    if ($LASTEXITCODE -ne 0) { throw "core dependency install failed." }
} else {
    if (-not (Test-Path $Requirements)) { throw "Requirements file not found: '$Requirements' (or pass -RelaxPins)." }
    # Normalize to UTF-8. Detect from the BYTES so it survives any save format an editor
    # produces -- UTF-16 LE/BE with OR without a BOM (pip can't parse those), or UTF-8.
    Info "Normalizing requirements to UTF-8"
    $reqUtf8 = Join-Path $env:TEMP 'ati-requirements-utf8.txt'
    $bytes = [System.IO.File]::ReadAllBytes($Requirements)
    if     ($bytes.Length -ge 2 -and $bytes[0] -eq 0xFF -and $bytes[1] -eq 0xFE) { $enc = [System.Text.Encoding]::Unicode }            # UTF-16 LE + BOM
    elseif ($bytes.Length -ge 2 -and $bytes[0] -eq 0xFE -and $bytes[1] -eq 0xFF) { $enc = [System.Text.Encoding]::BigEndianUnicode }   # UTF-16 BE + BOM
    elseif ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) { $enc = [System.Text.Encoding]::UTF8 }  # UTF-8 + BOM
    elseif (($bytes | Select-Object -First 400) -contains 0) { $enc = [System.Text.Encoding]::Unicode }  # null bytes, no BOM -> UTF-16 LE
    else { $enc = [System.Text.Encoding]::UTF8 }
    $text = $enc.GetString($bytes).TrimStart([char]0xFEFF)
    [System.IO.File]::WriteAllText($reqUtf8, $text, (New-Object System.Text.UTF8Encoding($false)))
    Info "Installing app requirements from $Requirements"
    & $venvPy -m pip install -r $reqUtf8
    if ($LASTEXITCODE -ne 0) {
        Warn "pip install -r failed. Re-run with -RelaxPins to install the pinned runtime deps directly,"
        Warn "or check the error above for a package needing a different version."
        throw "Dependency install failed."
    }
}
if (-not (Test-Path $wfastcgi)) { throw "wfastcgi.py not found at '$wfastcgi' after install." }
Good "Dependencies installed."

# --- 3. Register the FastCGI application (matches the handler in step 5) ----
$apphost   = 'MACHINE/WEBROOT/APPHOST'
$appFilter = "system.webServer/fastCgi/application[@fullPath='$venvPy' and @arguments='$wfastcgi']"
if (-not (Get-WebConfiguration -PSPath $apphost -Filter $appFilter -ErrorAction SilentlyContinue)) {
    Info "Registering FastCGI application"
    Add-WebConfiguration -PSPath $apphost -Filter 'system.webServer/fastCgi' -Value @{ fullPath = $venvPy; arguments = $wfastcgi }
} else {
    Info "FastCGI application already registered"
}
Set-WebConfigurationProperty -PSPath $apphost -Filter $appFilter -Name 'instanceMaxRequests' -Value 10000
Set-WebConfigurationProperty -PSPath $apphost -Filter $appFilter -Name 'activityTimeout'     -Value 600
Set-WebConfigurationProperty -PSPath $apphost -Filter $appFilter -Name 'requestTimeout'      -Value 600
Set-WebConfigurationProperty -PSPath $apphost -Filter $appFilter -Name 'idleTimeout'         -Value 300
Good "FastCGI app: $venvPy|$wfastcgi"

# --- 4. App pool: No Managed Code ------------------------------------------
if (-not (Test-Path "IIS:\AppPools\$AppPoolName")) {
    Info "Creating app pool '$AppPoolName'"
    New-WebAppPool -Name $AppPoolName | Out-Null
}
Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name 'managedRuntimeVersion' -Value ''   # "No Managed Code"
try {
    Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name 'startMode' -Value 'AlwaysRunning'
    Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name 'processModel.idleTimeout' -Value ([TimeSpan]::Zero)
} catch { Warn "Could not set startMode/idleTimeout (non-fatal): $($_.Exception.Message)" }
Good "App pool '$AppPoolName' -> No Managed Code"

if ($SiteName) {
    Info "Assigning app pool '$AppPoolName' to site '$SiteName'"
    Set-ItemProperty "IIS:\Sites\$SiteName" -Name applicationPool -Value $AppPoolName
}

# --- 5. web.config: handler scriptProcessor EXACTLY matches the FastCGI app -
if (-not $SkipWebConfig) {
    $webConfigPath   = Join-Path $SiteRoot 'web.config'
    $scriptProcessor = "$venvPy|$wfastcgi"

    # Read the existing appSettings so a re-run that omits a value PRESERVES it
    # (you don't have to re-pass -FlaskSecretKey / -DatabaseUrl every time).
    $existing = @{}
    if (Test-Path $webConfigPath) {
        $backup = "$webConfigPath.bak-" + (Get-Date -Format 'yyyyMMdd-HHmmss')
        Copy-Item $webConfigPath $backup
        Info "Backed up web.config -> $backup"
        try {
            [xml]$curXml = Get-Content -Raw -Path $webConfigPath
            foreach ($a in $curXml.configuration.appSettings.add) {
                if ($a.key) { $existing[[string]$a.key] = [string]$a.value }
            }
        } catch { Warn "Could not parse existing web.config appSettings (continuing): $($_.Exception.Message)" }
    }

    function Resolve-AppSetting([string]$key, [string]$paramValue, [bool]$wasPassed, [hashtable]$existing, [string]$default) {
        if ($wasPassed) { return $paramValue }
        if ($existing.ContainsKey($key)) { return $existing[$key] }
        return $default
    }
    function Xml-Esc([string]$s) { if ($null -eq $s) { return '' } else { return [System.Security.SecurityElement]::Escape($s) } }

    $b      = $PSBoundParameters
    $secret = Resolve-AppSetting 'FLASK_SECRET_KEY'      $FlaskSecretKey      $b.ContainsKey('FlaskSecretKey')      $existing ''
    $dburl  = Resolve-AppSetting 'DATABASE_URL'          $DatabaseUrl         $b.ContainsKey('DatabaseUrl')         $existing ''
    $neodb  = Resolve-AppSetting 'NEO4J_DATABASE'        $Neo4jDatabase       $b.ContainsKey('Neo4jDatabase')       $existing 'neo4j'
    $fenv   = Resolve-AppSetting 'FLASK_ENV'             $FlaskEnv            $b.ContainsKey('FlaskEnv')            $existing 'production'
    $aenf   = Resolve-AppSetting 'AUTH_ENFORCED'         $AuthEnforced        $b.ContainsKey('AuthEnforced')        $existing '1'
    $aprov  = Resolve-AppSetting 'AUTH_PROVIDER'         $AuthProvider        $b.ContainsKey('AuthProvider')        $existing 'local'
    $aadm   = Resolve-AppSetting 'AUTH_ADMINS'           $AuthAdmins          $b.ContainsKey('AuthAdmins')          $existing ''
    $aallow = Resolve-AppSetting 'AUTH_ALLOWED_USERS'    $AuthAllowedUsers    $b.ContainsKey('AuthAllowedUsers')    $existing ''
    $adbp   = Resolve-AppSetting 'AUTH_DB_PATH'          $AuthDbPath          $b.ContainsKey('AuthDbPath')          $existing 'C:\www\ati\data\auth_users.sqlite3'
    $asess  = Resolve-AppSetting 'AUTH_SESSION_HOURS'    $AuthSessionHours    $b.ContainsKey('AuthSessionHours')    $existing '12'
    $scook  = Resolve-AppSetting 'SESSION_COOKIE_SECURE' $SessionCookieSecure $b.ContainsKey('SessionCookieSecure') $existing '0'
    $cors   = Resolve-AppSetting 'CORS_ORIGINS'          $CorsOrigins         $b.ContainsKey('CorsOrigins')         $existing ''
    $dbg    = Resolve-AppSetting 'DEBUG'                 $Debug               $b.ContainsKey('Debug')               $existing 'False'
    $tst    = Resolve-AppSetting 'TESTING'               $Testing             $b.ContainsKey('Testing')             $existing 'False'
    $asTok  = Resolve-AppSetting 'ASANA_ACCESS_TOKEN'    $AsanaAccessToken    $b.ContainsKey('AsanaAccessToken')    $existing ''
    $asWs   = Resolve-AppSetting 'ASANA_WORKSPACE_GID'   $AsanaWorkspaceGid   $b.ContainsKey('AsanaWorkspaceGid')   $existing ''
    $asTeam = Resolve-AppSetting 'ASANA_TEAM_GID'        $AsanaTeamGid        $b.ContainsKey('AsanaTeamGid')        $existing ''
    $asUrl  = Resolve-AppSetting 'ASANA_BASE_URL'        $AsanaBaseUrl        $b.ContainsKey('AsanaBaseUrl')        $existing ''

    # Required, with the same fail-fast the app enforces at boot (app/__init__.py).
    if ([string]::IsNullOrWhiteSpace($secret)) {
        throw "FLASK_SECRET_KEY is required. Pass -FlaskSecretKey (generate: python -c ""import secrets; print(secrets.token_hex(32))"") or keep it in the existing web.config."
    }
    if ($secret.Trim().Length -lt 32 -or $secret -match 'REPLACE_WITH|PASTE-|changeme|^secret$') {
        throw "FLASK_SECRET_KEY is too short or a placeholder. Provide a real 64-hex key."
    }
    if ([string]::IsNullOrWhiteSpace($dburl)) {
        throw "DATABASE_URL is required. Pass -DatabaseUrl 'bolt://USER:PASSWORD@HOST:7687' or keep it in the existing web.config."
    }

    $webConfig = @"
<configuration>
  <system.webServer>
    <handlers>
      <add name="AtiHandler"
           path="*"
           verb="*"
           modules="FastCgiModule"
           scriptProcessor="$scriptProcessor"
           resourceType="Unspecified"
           requireAccess="Script" />
    </handlers>
    <httpErrors errorMode="Detailed" />
  </system.webServer>
  <appSettings>
    <!-- wfastcgi -->
    <add key="PYTHONPATH" value="$(Xml-Esc $SiteRoot)" />
    <add key="WSGI_HANDLER" value="$(Xml-Esc $WsgiHandler)" />
    <add key="WSGI_LOG" value="$(Xml-Esc $LogFile)" />
    <add key="WSGI_DEBUG" value="$(Xml-Esc $WsgiDebug)" />
    <!-- Flask runtime (production single source of truth) -->
    <add key="FLASK_ENV" value="$(Xml-Esc $fenv)" />
    <add key="FLASK_SECRET_KEY" value="$(Xml-Esc $secret)" />
    <add key="DEBUG" value="$(Xml-Esc $dbg)" />
    <add key="TESTING" value="$(Xml-Esc $tst)" />
    <!-- Database -->
    <add key="DATABASE_URL" value="$(Xml-Esc $dburl)" />
    <add key="NEO4J_DATABASE" value="$(Xml-Esc $neodb)" />
    <!-- CORS (usually empty for same-origin IIS) -->
    <add key="CORS_ORIGINS" value="$(Xml-Esc $cors)" />
    <!-- Auth -->
    <add key="AUTH_ENFORCED" value="$(Xml-Esc $aenf)" />
    <add key="AUTH_PROVIDER" value="$(Xml-Esc $aprov)" />
    <add key="AUTH_ADMINS" value="$(Xml-Esc $aadm)" />
    <add key="AUTH_ALLOWED_USERS" value="$(Xml-Esc $aallow)" />
    <add key="AUTH_DB_PATH" value="$(Xml-Esc $adbp)" />
    <add key="AUTH_SESSION_HOURS" value="$(Xml-Esc $asess)" />
    <add key="SESSION_COOKIE_SECURE" value="$(Xml-Esc $scook)" />
    <!-- Asana connector (empty unless the /asana endpoint is used) -->
    <add key="ASANA_ACCESS_TOKEN" value="$(Xml-Esc $asTok)" />
    <add key="ASANA_WORKSPACE_GID" value="$(Xml-Esc $asWs)" />
    <add key="ASANA_TEAM_GID" value="$(Xml-Esc $asTeam)" />
    <add key="ASANA_BASE_URL" value="$(Xml-Esc $asUrl)" />
  </appSettings>
  <system.web>
    <customErrors mode="Off" />
  </system.web>
</configuration>
"@
    Set-Content -Path $webConfigPath -Value $webConfig -Encoding UTF8
    Good "Wrote $webConfigPath (appSettings = the app's full production config)"
}

# --- 6. Filesystem permissions ---------------------------------------------
Info "Granting IIS_IUSRS read/execute on app + venv, write on the log"
& icacls $SiteRoot /grant "IIS_IUSRS:(OI)(CI)(RX)" /T /Q | Out-Null
& icacls $VenvPath /grant "IIS_IUSRS:(OI)(CI)(RX)" /T /Q | Out-Null
if (-not (Test-Path $LogFile)) { New-Item -ItemType File -Path $LogFile | Out-Null }
& icacls $LogFile  /grant "IIS_IUSRS:(M)" /Q | Out-Null
Good "Permissions applied"

# --- 7. Verify the app imports under the venv ------------------------------
Info "Verifying imports under Python 3.14..."
$probe = "import sys; sys.path.insert(0, r'$SiteRoot'); import flask, neomodel, neo4j; from app import create_app; print('IMPORT_OK')"
$result = & $venvPy -c $probe 2>&1
if ($result -match 'IMPORT_OK') {
    Good "App + core dependencies import cleanly."
} else {
    Warn "App did NOT import cleanly:"
    Write-Host ($result | Out-String) -ForegroundColor Yellow
    Warn "If it's ModuleNotFoundError for a feature lib, add it to the -RelaxPins list and re-run."
}

# --- 8. Recycle ------------------------------------------------------------
try { Restart-WebAppPool -Name $AppPoolName } catch { Start-WebAppPool -Name $AppPoolName -ErrorAction SilentlyContinue }
Good "App pool '$AppPoolName' recycled."
Write-Host ""
Write-Host "Browse the site. If it still 500s, open $LogFile for the Python traceback." -ForegroundColor Cyan
