// =====================================================================================
// Source-grounded rationales on every principle grounding, and conservative shapes.
// Run 2026-10-07 by Daniel Fontaine.
//
// WHY
//   Phases 2 and 3 wrote each rationale as a short reason for the fit. This pass rewrites
//   them to state what each source provides, in the style of the user's reference,
//   principle:shared-responsibility-requiring-coordination (curate_2026_10_07_shared_
//   responsibility_rationales.cypher). That principle is NOT touched here: not its
//   rationales, not its shapes.
//
// METHOD
//   Every derives_from edge was paired with its source passage, found in the stored raw_text
//   by the edge's quote or, without a quote, by its provision (scripts/build_windows.py,
//   +/-520 chars). Each rationale states only what that passage, or the surrounding
//   provision, says. Two claims outside the windows were checked before writing:
//   28 CFR 35.164 (same limit for communications) and 29 U.S.C. 794(a).
//   Only `rationale` and `assessed_date` change on the 59 edges. provision, grounding_kind
//   and quote are untouched.
//
// WHERE A SOURCE HAS NO TEXT, THE RATIONALE SAYS SO
//   Gov Code 11135 (no stored text; every copy refused retrieval). Section 508 statute
//   node: its stored source is a Section508.gov page that links to 29 U.S.C. 794d without
//   reproducing it, so four edges say the statute's text is not in the graph.
//
// SHAPES (principle -[:shapes]-> UniversalDescriptor, the convention the 7 existing edges use)
//   Added only where the principle's own description_full names what the element models;
//   each edge's `basis` is that phrase, checked verbatim against the principle text.
//   13 edges: StatusLevel, Asset x3, Guideline, Component, YearSuccessEvidence,
//   ProgressUpdate, Interface, TAAP x2, Vendor, field:Interface.audience.
//   Deliberately left unshaped: prioritization-by-impact (names "priority levels on tracked
//   work"; no descriptor models a priority field), local-adaptation-flexibility (about the
//   schema as a whole), notice, bounded duty, parallel duties, federal funding, state law,
//   program-viewed-in-its-entirety, universal design (no element named), and
//   institution-wide-responsibility (no description_full at all).
//
// VALIDATE FIRST
//   python -m app.database.cypher_runner.run_file app/database/batch/auto-assignments/curate_2026_10_07_principle_rationales_and_shapes.cypher
//   python -m app.database.cypher_runner.run_file app/database/batch/auto-assignments/curate_2026_10_07_principle_rationales_and_shapes.cypher --execute
// =====================================================================================

// --- 1. Rationales (59 edges) -------------------------------------------------------
UNWIND [
  {h: "principle:audience-determines-governing-duty", g: "28513850e4794975925f7538fdc096ac", why: "Section 35.140(a) prohibits disability discrimination in employment under any service, program, or activity of a public entity. Section 35.140(b)(1) applies Title I's requirements, as set out in the EEOC's 29 CFR Part 1630, to that employment when the public entity is also subject to Title I. Section 35.140(b)(2) applies DOJ's Section 504 employment rules in 28 CFR Part 41 when it is not."},
  {h: "principle:audience-determines-governing-duty", g: "9c157a65c4b34ae7804c8c6fbda8e476", why: "Section 12112(b) lists what discrimination against a qualified individual includes. Paragraph (5)(A) includes not making reasonable accommodations to the known physical or mental limitations of an applicant or employee unless the employer shows undue hardship. Paragraph (5)(B) includes denying employment because of the need to make such an accommodation."},
  {h: "principle:audience-determines-governing-duty", g: "ae34235450c4443b8b4298540b677903", why: "The order commits the CSU to reasonable accommodation for employees and applicants with disabilities unless it would impose an undue hardship. Each campus and the Chancellor's Office must post a written accommodation procedure on its Human Resources website and engage in a timely, good faith, interactive process in response to a request. Accommodation records must be kept confidential and apart from the personnel file."},
  {h: "principle:audience-determines-governing-duty", g: "63c25f78f69b4bc0b0db52da6df7fec4", why: "In the preamble, DOJ answers commenters who asked whether subpart H covers internal content used only by employees. It states that subpart H covers the web content and mobile apps a public entity provides or makes available within Title II's scope, and that subpart H is not issued under Title I. It adds that complying with subpart H does not relieve a public entity of its separate Title I employment obligations, giving accommodations for a web developer with a disability as an example."},
  {h: "principle:audience-determines-governing-duty", g: "a4311ce7e4f44da5ab565b9ceb348d51", why: "Section 1630.2(o) defines reasonable accommodation, including making facilities accessible, job restructuring, modified schedules, reassignment, acquiring or modifying equipment, and adjusting examinations and training materials. Paragraph (o)(3) says finding the appropriate accommodation may require the employer to start an informal, interactive process with the individual. That process should identify the precise limitations and the accommodations that could overcome them."},
  {h: "principle:bounded-duty-burden-limits", g: "28513850e4794975925f7538fdc096ac", why: "Section 35.150(a)(3) says the program-access duty does not require any action the public entity can show would fundamentally alter a service, program, or activity or impose undue financial and administrative burdens. The public entity carries the burden of proving it. Section 35.164 applies the same limit, with the same burden, to communications."},
  {h: "principle:bounded-duty-burden-limits", g: "e668e2199b7e4927b548c179e4bf4b27", why: "Section 12131(2) defines a qualified individual with a disability as one who meets a program's essential eligibility requirements with or without reasonable modifications to rules, policies, or practices, removal of barriers, or auxiliary aids and services. The Title II sections stored here, 12131 to 12134, state no undue burden or fundamental alteration limit. Those limits appear in the regulations at 28 CFR 35.150(a)(3), 35.164, and 35.204."},
  {h: "principle:bounded-duty-burden-limits", g: "e6f402d1454048baa0774281e82e64d7", why: "The policy commits the CSU to provide appropriate accommodations and support services and to make reasonable modifications in policies, practices, or procedures when necessary to avoid discrimination. It makes an exception where providing them is shown to fundamentally alter the service, program, or activity or to create undue financial or administrative burdens."},
  {h: "principle:bounded-duty-burden-limits", g: "63c25f78f69b4bc0b0db52da6df7fec4", why: "Section 35.204 says compliance with subpart H does not require actions that would fundamentally alter a service, program, or activity or impose undue financial and administrative burdens. The public entity carries the burden of proof, and the decision must be made by the head of the entity or a designee after considering all available resources, with a written statement of reasons. Where an action would cause such alteration or burdens, the entity must take any other action that ensures people with disabilities receive its benefits or services to the maximum extent possible."},
  {h: "principle:capability-maturity-over-binary-compliance", g: "ae8c836ef5354e18afdedf905935ada7", why: "Under Key Strategies, the policy says the CSU uses a capabilities maturity strategy, focused on continuously improving and institutionalizing processes that reliably deliver accessible services. It assesses campus performance on success indicators by levels of organizational capability: Not Started, Initiated, Defined, Established, Managed, and Optimized. Success indicators assigned a timeline must reach the Established baseline within it."},
  {h: "principle:closest-to-capacity", g: "e668e2199b7e4927b548c179e4bf4b27", why: "Section 12132 prohibits excluding a qualified individual with a disability from, or denying them the benefits of, a public entity's services, programs, or activities. It places the obligation on the public entity. It says nothing about how responsibility is divided among units inside the entity."},
  {h: "principle:closest-to-capacity", g: "2d9ef5513cca4b4a958c1f3e6a84aac6", why: "The Section 508 node's stored source is a Section508.gov page that links to 29 U.S.C. 794d without reproducing it. The statute's own allocation of duties is therefore not in the graph, and no stored text confirms or contradicts this design choice."},
  {h: "principle:conformance-to-an-external-technical-standard", g: "63c25f78f69b4bc0b0db52da6df7fec4", why: "In its analysis of 35.200, DOJ concludes that subpart H requires conformance to WCAG 2.1 Level AA as a whole on one compliance timeframe, declining a separate timeline for the live captioning criterion. It then summarizes 35.200 as requiring web content and mobile apps to comply with WCAG 2.1 Level AA and introduces the exceptions in 35.201. Section 35.202(b) incorporates WCAG 2.1 by reference."},
  {h: "principle:conformance-to-an-external-technical-standard", g: "7b8f0d60d1cc4f4f8cfc35fdbad73852", why: "WCAG 2.1 section 5.2 sets the conformance requirements for a web page. For Level AA conformance, the page satisfies all Level A and Level AA success criteria, or a Level AA conforming alternate version is provided."},
  {h: "principle:continuous-sustained-remediation", g: "ae8c836ef5354e18afdedf905935ada7", why: "Under Key Strategies, the policy's continuous quality improvement component says some ATI goals need investments and procedural changes that take time to deploy across the CSU. It states that barriers develop over years and that remediation will sometimes take years. During that period the CSU should achieve incremental improvements in barrier removal each year."},
  {h: "principle:equally-effective-access", g: "28513850e4794975925f7538fdc096ac", why: "Section 35.130(b)(1) lists actions a public entity may not take, directly or through contractual, licensing, or other arrangements, when providing any aid, benefit, or service. Paragraph (iii) prohibits an aid, benefit, or service that is not as effective in affording equal opportunity to obtain the same result, gain the same benefit, or reach the same level of achievement as that provided to others. Paragraph (iv) allows different or separate aids only where necessary to provide aids that are as effective as those provided to others."},
  {h: "principle:equally-effective-access", g: "e668e2199b7e4927b548c179e4bf4b27", why: "Section 12132 prohibits excluding a qualified individual with a disability from participation in, or denying them the benefits of, a public entity's services, programs, or activities, and prohibits discrimination by the entity. It does not define equal effectiveness. The regulation does, at 28 CFR 35.130(b)(1)(iii)."},
  {h: "principle:equally-effective-access", g: "ae8c836ef5354e18afdedf905935ada7", why: "The policy's Vision lists three principles that drive the ATI. The second requires technology for individuals with disabilities to provide access to obtain the same result, gain the same benefit, or have the same opportunity to reach the same level of achievement as persons without disabilities."},
  {h: "principle:equally-effective-access", g: "e6f402d1454048baa0774281e82e64d7", why: "The policy's stated purpose is that no qualified individual with a disability be excluded from CSU services, programs, or activities on the basis of disability. It commits the CSU to provide appropriate accommodations, support services, and reasonable modifications when necessary to avoid discrimination, subject to the fundamental alteration and undue burden limits."},
  {h: "principle:equally-effective-access", g: "99d4a68d95e7413eac49fb5c8083bf2a", why: "Section 104.4(b)(1) lists actions a recipient may not take, directly or through contractual, licensing, or other arrangements, in providing any aid, benefit, or service. Paragraph (iii) prohibits an aid, benefit, or service that is not as effective as that provided to others. Paragraph (iv) permits different or separate aids only where necessary to make them as effective as those provided to others."},
  {h: "principle:federal-funding-reaches-every-operation", g: "99d4a68d95e7413eac49fb5c8083bf2a", why: "Section 104.3(k) defines program or activity as all of the operations of the listed entities. Paragraph (k)(2)(i) names a college, university, or other postsecondary institution, or a public system of higher education."},
  {h: "principle:federal-funding-reaches-every-operation", g: "17825dbe87af4c01baa232ab390136b1", why: "Section 794(a) bars excluding, denying benefits to, or discriminating against an otherwise qualified individual solely by reason of disability under any program or activity receiving federal financial assistance. Section 794(b) defines program or activity as all of the operations of the listed entities. Paragraph (b)(2)(A) names a college, university, or other postsecondary institution, or a public system of higher education."},
  {h: "principle:institution-wide-responsibility", g: "ae8c836ef5354e18afdedf905935ada7", why: "The policy's Vision says all CSU programs, services, and activities should be accessible to students, staff, faculty, and the general public, across all technology used to deliver academic, student, information technology, and auxiliary services. The first of its three driving principles calls technology accessibility an institution-wide responsibility that requires commitment and involvement from leadership across the enterprise."},
  {h: "principle:local-adaptation-flexibility", g: "ae8c836ef5354e18afdedf905935ada7", why: "The policy's Implementation Approach recognizes that each campus faces unique challenges in implementing the ATI. It says the approach was developed with the Executive Sponsors Steering Committee and the ATI Priority Area Communities of Practice to give campuses adequate flexibility to manage implementation. Campuses must still reach the Established baseline on success indicators with timelines, and they choose other indicators to work on according to their capacity."},
  {h: "principle:notice-as-part-of-access", g: "28513850e4794975925f7538fdc096ac", why: "Section 35.106 requires a public entity to make information about Part 35, and how it applies to the entity's services, programs, and activities, available to applicants, participants, beneficiaries, and other interested persons. The information must be provided in the manner the head of the entity finds necessary to inform them of their protections against discrimination."},
  {h: "principle:notice-as-part-of-access", g: "e668e2199b7e4927b548c179e4bf4b27", why: "Section 12132 prohibits exclusion from, denial of the benefits of, and discrimination in a public entity's services, programs, or activities. It contains no notice requirement. The notice duty is in the regulation at 28 CFR 35.106."},
  {h: "principle:parallel-duties-conformance-and-accommodation", g: "28513850e4794975925f7538fdc096ac", why: "Section 35.160(a)(1) requires a public entity to take appropriate steps so that communications with applicants, participants, members of the public, and companions with disabilities are as effective as communications with others. Section 35.160(b)(1) requires it to furnish appropriate auxiliary aids and services where necessary to afford an equal opportunity to participate in and enjoy the benefits of its services, programs, and activities."},
  {h: "principle:parallel-duties-conformance-and-accommodation", g: "ae34235450c4443b8b4298540b677903", why: "The order requires the Chancellor's Office, with the systemwide advisory committee, to maintain and publish procedures for accommodating students with disabilities. It requires the CSU to conduct an interactive process with each student with a disability to assess the functional impact of the disability and identify reasonable accommodations, so the student can participate on terms equal to others. The CSU need not provide the accommodation requested, must provide the same benefits and opportunity to reach the same level of achievement, and may not charge the student for it."},
  {h: "principle:parallel-duties-conformance-and-accommodation", g: "63c25f78f69b4bc0b0db52da6df7fec4", why: "In discussing compliance dates, DOJ agrees with commenters that public entities must meet all of Title II's existing requirements both before and after their subpart H compliance date. It names those requirements as ensuring equal access, ensuring effective communication, and making reasonable modifications to avoid discrimination on the basis of disability."},
  {h: "principle:parallel-duties-conformance-and-accommodation", g: "99d4a68d95e7413eac49fb5c8083bf2a", why: "Section 104.44(d)(1) requires a postsecondary recipient to take the steps necessary so that no student with impaired sensory, manual, or speaking skills is denied benefits, excluded, or otherwise discriminated against because educational auxiliary aids are absent. Section 104.44(d)(2) lists examples such as taped texts, interpreters, and readers in libraries, and excludes devices and services of a personal nature."},
  {h: "principle:prioritization-by-impact", g: "ae8c836ef5354e18afdedf905935ada7", why: "Under Key Strategies, the policy's prioritization component says the ATI covers a broad range of technology goals across all university programs. Because staffing, time, and tools are finite each year, campuses should select implementation activities that target the barriers with the greatest impact. The policy's plan-review section directs campuses to use the ATI Prioritization Framework, or a comparable process, to weigh impact, probability, and capacity."},
  {h: "principle:program-accessibility-as-proactive-duty", g: "28513850e4794975925f7538fdc096ac", why: "Section 35.149 prohibits excluding a qualified individual from a public entity's programs because its facilities are inaccessible, except as 35.150 provides. Section 35.150(a) requires each service, program, or activity, viewed in its entirety, to be readily accessible to and usable by individuals with disabilities. It does not necessarily require every existing facility to be accessible, and it does not require actions shown to cause a fundamental alteration or undue burdens."},
  {h: "principle:program-accessibility-as-proactive-duty", g: "e668e2199b7e4927b548c179e4bf4b27", why: "Section 12132 prohibits excluding a qualified individual with a disability from, or denying them the benefits of, a public entity's services, programs, or activities. It is the general prohibition the Title II regulations carry out, including program access at 28 CFR 35.150 and web conformance at subpart H."},
  {h: "principle:program-accessibility-as-proactive-duty", g: "247ccd3b219d4cec85ecbc2e57be154c", why: "Section 7405 opens with a legislative finding that using electronic or information technology is often an essential function of employment. Subsection (a) requires state governmental entities that develop, procure, maintain, or use such technology to comply with Section 508 and its regulations in 36 CFR Part 1194. Subsection (b) requires contractors with entities subject to Section 11135 to agree to respond to and resolve accessibility complaints about their products or services."},
  {h: "principle:program-accessibility-as-proactive-duty", g: "63c25f78f69b4bc0b0db52da6df7fec4", why: "Section 35.200(a) requires a public entity to ensure that web content and mobile apps it provides or makes available, directly or through contractual, licensing, or other arrangements, are readily accessible to and usable by individuals with disabilities. The rest of 35.200 sets the technical standard and the compliance timelines."},
  {h: "principle:program-accessibility-as-proactive-duty", g: "2d9ef5513cca4b4a958c1f3e6a84aac6", why: "The Section 508 node's stored source is a Section508.gov page that links to 29 U.S.C. 794d without reproducing it, so the statute's text is not in the graph. Section 508 reaches the CSU through Government Code 7405, whose text is stored."},
  {h: "principle:program-viewed-in-its-entirety", g: "28513850e4794975925f7538fdc096ac", why: "Section 35.150(b)(1) lists methods a public entity may use, including reassigning services to accessible buildings, delivering services at alternate accessible sites, altering facilities, or any other method that makes its programs accessible. It does not require structural changes where other methods are effective. In choosing among methods, the entity must give priority to those that offer programs in the most integrated setting appropriate."},
  {h: "principle:program-viewed-in-its-entirety", g: "63c25f78f69b4bc0b0db52da6df7fec4", why: "Section 35.202(a) allows a public entity to use conforming alternate versions of web content, as WCAG 2.1 defines them, only where direct accessibility is not possible because of technical or legal limitations. Section 35.202(b) incorporates WCAG 2.1 by reference."},
  {h: "principle:program-viewed-in-its-entirety", g: "99d4a68d95e7413eac49fb5c8083bf2a", why: "Section 104.21 prohibits denying a qualified person the benefits of a recipient's programs because its facilities are inaccessible. Section 104.22(a) requires each program or activity, viewed in its entirety, to be readily accessible, without requiring every facility or part of a facility to be. Section 104.22(b) allows methods such as redesigning equipment and reassigning classes to accessible buildings, and does not require structural changes where other methods are effective."},
  {h: "principle:proportionate-remedy", g: "e668e2199b7e4927b548c179e4bf4b27", why: "Section 12132 states a general prohibition on exclusion, denial of benefits, and discrimination by a public entity. It contains no scale for the severity of a barrier or the weight of a remedy."},
  {h: "principle:proportionate-remedy", g: "63c25f78f69b4bc0b0db52da6df7fec4", why: "DOJ explains that the exceptions in 35.201 aim to keep current, commonly used, and widely needed content accessible while making compliance feasible, by letting public entities make frequently used or high-impact content conform first. The excepted categories are archived web content, certain preexisting conventional electronic documents, third-party content, individualized secured documents, and preexisting social media posts. Section 35.205 treats noncompliance as meeting 35.200 where its impact is so minimal that people with disabilities can still obtain the same information, interactions, transactions, and benefits with substantially equivalent timeliness, privacy, independence, and ease of use."},
  {h: "principle:state-law-adopts-the-federal-standard", g: "ae8c836ef5354e18afdedf905935ada7", why: "The policy's Background states that the ADA and Section 504 require equal access to programs, services, and activities. It states that Government Code 11135 applies Section 508 to state entities and to the CSU, and that Section 508 was enacted to eliminate barriers in information technology. It names Executive Order 1111 as the CSU's policy statement on accessibility."},
  {h: "principle:state-law-adopts-the-federal-standard", g: "849abdeb538443e8be1e93e3b280d336", why: "The text of Government Code 11135 is not stored in the graph; the leginfo, Justia, and FindLaw copies all refused automated retrieval. The claim that 11135 applies Section 508 to the CSU is recorded here from the CSU's ATI policy, not from the statute."},
  {h: "principle:state-law-adopts-the-federal-standard", g: "247ccd3b219d4cec85ecbc2e57be154c", why: "Section 7405(a) requires state governmental entities that develop, procure, maintain, or use electronic or information technology, either indirectly or through state funds used by other entities, to comply with Section 508 and its regulations in 36 CFR Part 1194. The legislative finding before it ties the requirement to the employment of people with disabilities. Section 7405(b) requires contractors with entities subject to Section 11135 to agree to respond to and resolve accessibility complaints about their products or services."},
  {h: "principle:state-law-adopts-the-federal-standard", g: "2d9ef5513cca4b4a958c1f3e6a84aac6", why: "The Section 508 node's stored source links to 29 U.S.C. 794d without reproducing it, so the statute's scope is not in the graph. Government Code 7405, whose text is stored, is the provision that applies Section 508 to state governmental entities."},
  {h: "principle:time-bound-alternative-when-not-conformant", g: "e668e2199b7e4927b548c179e4bf4b27", why: "Section 12132 states a general prohibition on exclusion, denial of benefits, and discrimination by a public entity. It provides no mechanism for interim alternative access during remediation."},
  {h: "principle:time-bound-alternative-when-not-conformant", g: "749610aedade4c709d784c10cd36dbb0", why: "The CSU's TAAP page describes the Temporary Alternative Access Plan, formerly the EEAAP, as an interim measure while vendors remediate known barriers that affect core functionality. Version 3.3 positions TAAPs as temporary risk-management tools that do not indicate Title II compliance. It requires campuses to document vendor notification of severe barriers and remediation expectations, and requires formal executive acknowledgment of ongoing risk when a TAAP continues without vendor progress."},
  {h: "principle:time-bound-alternative-when-not-conformant", g: "ae8c836ef5354e18afdedf905935ada7", why: "Among its Procurement Accessibility Goals, the policy requires procurement processes that follow Section 508 for all acquired ICT. It requires Equally Effective Access Plans for ICT products that are not fully Section 508 compliant. It also requires training and outreach for procurement stakeholders and an annually reviewed ATI Procurement Plan."},
  {h: "principle:time-bound-alternative-when-not-conformant", g: "63c25f78f69b4bc0b0db52da6df7fec4", why: "Section 35.202(a) permits conforming alternate versions of web content only where direct accessibility is not possible because of technical or legal limitations. It provides no general interim alternative while content is remediated. The other-action duty in 35.204 applies only after a documented fundamental alteration or undue burden determination."},
  {h: "principle:universal-design-over-accommodation", g: "e668e2199b7e4927b548c179e4bf4b27", why: "Section 12132 states a general prohibition on exclusion, denial of benefits, and discrimination by a public entity. It does not mention universal design."},
  {h: "principle:universal-design-over-accommodation", g: "ae8c836ef5354e18afdedf905935ada7", why: "The third of the policy's driving principles says implementing Universal Design principles should reduce the need for, and costs of, individual accommodations for inaccessible technology products. It sits in the Vision alongside institution-wide responsibility and equal effectiveness."},
  {h: "principle:universal-design-over-accommodation", g: "247ccd3b219d4cec85ecbc2e57be154c", why: "Section 7405(a) requires state entities to apply Section 508 when they develop, procure, maintain, or use technology, which applies the standard before anyone asks for access. It does not mention universal design or accommodation."},
  {h: "principle:universal-design-over-accommodation", g: "2d9ef5513cca4b4a958c1f3e6a84aac6", why: "The Section 508 node's stored source links to 29 U.S.C. 794d without reproducing it, so whether the statute addresses universal design cannot be read from the graph."},
  {h: "principle:vendor-leverage-procurement-as-accessibility-lever", g: "749610aedade4c709d784c10cd36dbb0", why: "In Step 3 of the CSU ATI procurement process, the ATI Reviewer conducts the accessibility review, approves or denies the acquisition, and for an approved acquisition obtains a vendor Accessibility Roadmap and creates a TAAP. The reviewer compiles contract requirements: a vendor-completed Accessibility Roadmap, an Accessibility Statement in the product, and an ongoing commitment to current Accessibility Conformance Reports. The reviewer sends these to the Buyer for the final contract or purchase order."},
  {h: "principle:vendor-leverage-procurement-as-accessibility-lever", g: "ae8c836ef5354e18afdedf905935ada7", why: "Under Key Strategies, the policy lists driving vendor improvements to product accessibility support as a component of the ATI. It says the CSU seeks to improve product accessibility through partnerships and by leveraging the procurement process. Its Procurement Accessibility Goals require procurement processes that follow Section 508 for all acquired ICT."},
  {h: "principle:vendor-leverage-procurement-as-accessibility-lever", g: "ae34235450c4443b8b4298540b677903", why: "Section VII requires any public solicitation process developed by a campus or the Chancellor's Office to comply with regulations and guidelines issued under the ADA and Government Code 11135. It also bars a solicitation from denying individuals with disabilities the opportunity to compete for a contract. Section VIII defines accessible as affording a person with a disability the same information, interactions, and services in an equally effective and equally integrated manner, with substantially equivalent ease of use."},
  {h: "principle:vendor-leverage-procurement-as-accessibility-lever", g: "247ccd3b219d4cec85ecbc2e57be154c", why: "Section 7405(a) requires state governmental entities to comply with Section 508 and 36 CFR Part 1194 when they procure electronic or information technology, as well as when they develop, maintain, or use it. Section 7405(b) requires any contractor providing such technology or related services to an entity subject to Section 11135 to agree to respond to and resolve accessibility complaints about its products or services."},
  {h: "principle:vendor-leverage-procurement-as-accessibility-lever", g: "63c25f78f69b4bc0b0db52da6df7fec4", why: "DOJ's overview states that subpart H sets technical requirements for web content that state and local governments provide or make available, directly or through contractual, licensing, or other arrangements. It defines web content to include text, images, sounds, videos, controls, animations, and conventional electronic documents. Content a public entity provides through a vendor arrangement is therefore within its duty."},
  {h: "principle:vendor-leverage-procurement-as-accessibility-lever", g: "34a1e0763aaa4b2c80dfb8cc672fbb36", why: "Section508.gov's guidance on defining accessibility criteria tells federal agencies to set criteria in solicitations, statements of work, and other procurement documents so the ICT they buy or build conforms to the Revised 508 Standards. It offers sample language and advises tailoring provisions, assessing the risk of inaccessible ICT, and using only clauses appropriate to the items purchased. The guidance is written for federal agencies."}
] AS row
MATCH (p:Principle {handle: row.h})-[r:derives_from]->(g {unique_id: row.g})
SET r.rationale = row.why, r.assessed_date = date("2026-10-07");

// --- 2. Shapes (13 edges, conservative) ---------------------------------------------
UNWIND [
  {h: "principle:capability-maturity-over-binary-compliance", d: "node_type:StatusLevel", basis: "the conceptual basis for representing status as graded maturity levels rather than a pass or fail flag"},
  {h: "principle:closest-to-capacity", d: "node_type:Asset", basis: "the conceptual basis for modeling stewardship (procure, develop, maintain, use) separately from remediation accountability"},
  {h: "principle:conformance-to-an-external-technical-standard", d: "node_type:Guideline", basis: "the treatment of the external standard as the authority"},
  {h: "principle:conformance-to-an-external-technical-standard", d: "node_type:Component", basis: "the authority that individuates components"},
  {h: "principle:continuous-sustained-remediation", d: "node_type:YearSuccessEvidence", basis: "the basis for the annual evidence cycle, for tracking progress across academic years"},
  {h: "principle:continuous-sustained-remediation", d: "node_type:ProgressUpdate", basis: "treating the trajectory of an effort as meaningful independent of its absolute status"},
  {h: "principle:program-accessibility-as-proactive-duty", d: "node_type:Interface", basis: "a standing obligation on the interfaces and assets the institution offers"},
  {h: "principle:program-accessibility-as-proactive-duty", d: "node_type:Asset", basis: "a standing obligation on the interfaces and assets the institution offers"},
  {h: "principle:time-bound-alternative-when-not-conformant", d: "node_type:TAAP", basis: "This grounds the alternate-access-plan instrument, its annual review and graded outcomes"},
  {h: "principle:time-bound-alternative-when-not-conformant", d: "node_type:Asset", basis: "the elevation signal when a non-conformant asset has no remediating work or covering alternative"},
  {h: "principle:proportionate-remedy", d: "node_type:TAAP", basis: "Formal alternative-access planning is the institution's answer to barriers severe enough to prevent people from performing essential functions"},
  {h: "principle:vendor-leverage-procurement-as-accessibility-lever", d: "node_type:Vendor", basis: "exercised through the procurement process and through partnership with vendors and publishers"},
  {h: "principle:audience-determines-governing-duty", d: "field:Interface.audience", basis: "Procurement and remediation planning have to identify the audience before they can identify the duty"}
] AS row
MATCH (p:Principle {handle: row.h})
MATCH (d:UniversalDescriptor {descriptor_handle: row.d})
MERGE (p)-[s:shapes]->(d)
ON CREATE SET s.added_date = date("2026-10-07"), s.basis = row.basis;
